### ISSUE TITLE
How can I pass header during websocket connection?

### ISSUE THREAD

**Issue by zhaoyi0113** [jjxxs/websocket-ts#23]
I have a websocket server which requires authentication by checking token in the header. How can I pass in headers?

**Comment by jjxxs** [comment]
Setting headers during the initial WebSocket-handshake is not supported by the Web API. This has nothing to do with this library, it's not supported by the browsers native WebSocket-class. 

Two ways to realize authentication:

1. Add your token as a query-param to the url, e.g. pass ```http://your-domain.com/api/v1/ws?auth=<your_token>```. The backend can now check if the token is valid and if it wants to accept the connection. However, this is **not recommended** since URLs can be logged, cached and might be exposed in your browser history.
2. Pass your token in the ```protocols```-parameter, e.g. ```new Websocket('your_url', ["Bearer <your_token>"])```
