### ISSUE TITLE
Browser !== window

### ISSUE THREAD

**Issue by AntonOfTheWoods** [jjxxs/websocket-ts#28]
`window` is not available in workers, `setTimeout` is, which makes using this largely impossible outside of the window context. Is there some reason to use `window.setTimeout` rather than nothing or `globalThis`?

**Comment by jjxxs** [comment]
thanks for the report. the reason i'm using the ```window``` object is due to how typescript resolves the ```setTimeout``` function. when resolved, typescript defaults to pulling in the node.js type definitions, which are incompatible with the browser context. this issue is discussed in more detail [here](https://github.com/Microsoft/TypeScript/issues/30128).

while it seems like a build or configuration issue, i've yet to find a definitive solution. for instance, setting the lib compiler option to "DOM" hasn't resolved the problem and the project will fail to build.

in the meantime, i've made some adjustments. could you please test the branch [wts-28_window_set_timeout](https://github.com/jjxxs/websocket-ts/tree/wts-28_window_set_timeout) and let me know if it addresses your concern? the change is minimal, see [af7fcd9](https://github.com/jjxxs/websocket-ts/compare/master...wts-28_window_set_timeout).

**Comment by AntonOfTheWoods** [comment]
> in the meantime, i've made some adjustments. could you please test the branch [wts-28_window_set_timeout](https://github.com/jjxxs/websocket-ts/tree/wts-28_window_set_timeout) and let me know if it addresses your concern? the change is minimal, see [af7fcd9](https://github.com/jjxxs/websocket-ts/compare/master...wts-28_window_set_timeout).

Yeah, that would work. It is annoying that they still haven't fixed it but a good old `as unknown as number` also fixes it. Actually I guess it won't pass if you don't do that, even with `globalThis`. My understanding is that the `as unknown as number` is the best fix at the moment, until the typescript devs fix their bug. At the moment I just copied all your code and made exactly these two fixes, so if you can merge this (+ `as unknown as number`) then I'll be able to remove it!

**Comment by jjxxs** [comment]
Fixed in [v2.1.5](https://github.com/jjxxs/websocket-ts/releases/tag/v2.1.5).

**Comment by AntonOfTheWoods** [comment]
Awesome, thanks!
